[provider]
cluster = "localnet"
wallet = "./keypairs/update-authority.json"

[programs.mainnet]
rewards_center = "ErbSL4EyyTrYPoVeUrs7VPpcf2LBS7mWbSv4ivv538hA"

[programs.devnet]
rewards_center = "ErbSL4EyyTrYPoVeUrs7VPpcf2LBS7mWbSv4ivv538hA"

[programs.testnet]
rewards_center = "ErbSL4EyyTrYPoVeUrs7VPpcf2LBS7mWbSv4ivv538hA"

[programs.localnet]
rewards_center = "ErbSL4EyyTrYPoVeUrs7VPpcf2LBS7mWbSv4ivv538hA"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-pool.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/stake-entry/stake-unstake-pnft.test.ts"

# [test]
# startup_wait = 10000